#!/usr/bin/env -S python3 -u
"""Main entry point for `slopspotter`."""

import argparse
import json
import logging
import os
import struct
import sys
from importlib.metadata import metadata
from typing import Any, Literal

from slopspotter import manifests
from slopspotter.constants import SLOPSPOTTER_VERSION, SUPPORTED_BROWSERS

logger = logging.getLogger(__name__)

logging.basicConfig(
    filename=os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "log.log"
    ),
    level=logging.DEBUG,
    encoding="utf-8",
    format="%(asctime)s - PID %(process)d [%(levelname)s]: %(message)s",
)


def get_message() -> dict[Literal["snippetId", "packages"], Any]:
    """Read a native message from STDIN and return it as a dictionary.

    On the application side, native messages are serialized using UTF-8 encoded
    JSON and are preceded with an unsigned 32-bit value containing the message
    length in native byte order.

    Returns:
        message_dict: JSON message as a Python dictionary
    """
    # Get 32-bit unsigned integer containing message length
    raw_length = sys.stdin.buffer.read(4)
    message_length = struct.unpack("@I", raw_length)[0]
    logging.debug("Message length: %d", message_length)
    if len(raw_length) == 0:
        return {}

    # Get the actual message, return as dict
    message_str = sys.stdin.buffer.read(message_length).decode("utf-8")
    logging.debug("Received message: %s", message_str)
    return json.loads(message_str)


def placeholder_package_results(name, language):
    """Create placeholder package result dict for the given package in language."""
    return {
        "name": name,
        "language": language,
        "result": {
            "riskLevel": "low",
            "score": 0.12,
            "summary": "Lorem ipsum dolor sit amet",
            "metadataUrl": "https://www.example.com",
        },
    }


def encode_message(message_content):
    """Encode a message for transmission, given its content.

    https://docs.python.org/3/library/json.html#basic-usage

    To get the most compact JSON representation, you should specify (',', ':')
    to eliminate whitespace. We want the most compact representation because
    the browser rejects # messages that exceed 1 MB.
    """
    logging.debug("encoding message")
    encoded_content = json.dumps(message_content, separators=(",", ":")).encode("utf-8")
    encoded_length = struct.pack("@I", len(encoded_content))
    return {"length": encoded_length, "content": encoded_content}


def send_message(encoded_message):
    """Send an encoded message to stdout."""
    sys.stdout.buffer.write(encoded_message["length"])
    sys.stdout.buffer.write(encoded_message["content"])
    sys.stdout.buffer.flush()


def main() -> int:
    """Main entry point for `slopspotter`."""
    logging.debug("starting __main__.main()")
    parser = argparse.ArgumentParser(
        prog="slopspotter",
        description=metadata("slopspotter")["Summary"],
    )
    parser.add_argument(
        "manifest_path",
        nargs="?",
        default="",
        help="The complete path to the app manifest (generated by the extension).",
    )
    parser.add_argument(
        "browser_settings",
        nargs="?",
        default="",
        help="The extension's ID (generated by the extension).",
    )
    parser.add_argument(
        "-i",
        "--install-manifests",
        choices=SUPPORTED_BROWSERS,
        help="Set up the native host to work with the given browser.",
    )
    parser.add_argument(
        "-V",
        "--version",
        action="store_true",
        help="Print the current version and exit.",
    )
    args = parser.parse_args(sys.argv[1:])
    logging.debug("Received args: " + str(vars(args)))

    if args.version:
        print(SLOPSPOTTER_VERSION)
        return 0

    if args.install_manifests:
        manifests.install_manifests(args.install_manifests)
        return 0

    if args.manifest_path == "" or args.browser_settings == "":
        print(
            f"Invalid manifest path or settings:"
            f"\n\t- '{args.manifest_path}'"
            f"\n\t- '{args.browser_settings}'"
            "\nSee `slopspotter --help` for more information"
        )
        return 1

    # Actual call-and-response
    message_dict = get_message()
    logging.debug("Snippet ID: %s", message_dict["snippetId"])
    logging.debug(
        "Packages: %s",
        [package_dict["name"] for package_dict in message_dict["packages"]],
    )
    response_dict = {
        "snippetId": message_dict["snippetId"],
        "packages": [
            placeholder_package_results(package_dict["name"], package_dict["language"])
            for package_dict in message_dict["packages"]
        ],
    }
    logging.debug("A")
    logging.debug("Response: %s", response_dict)
    encoded_message = encode_message(json.dumps(response_dict))
    send_message(encoded_message)
    logging.debug("__main__.main() complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
