#!/usr/bin/env -S python3 -u
"""Main entry point for `slopspotter`."""

import argparse
import logging
import os
import sys
from importlib.metadata import metadata

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    PreTrainedModel,
    PreTrainedTokenizer,
)

from slopspotter import manifests
from slopspotter.constants import SLOPSPOTTER_VERSION, SUPPORTED_BROWSERS
from slopspotter.messaging import NativeMessage
from slopspotter.scoring import handle_check_packages

logger = logging.getLogger(__name__)

logging.basicConfig(
    filename=os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "log.log"
    ),
    level=logging.DEBUG,
    encoding="utf-8",
    format="%(asctime)s - PID %(process)d [%(levelname)s]: %(message)s",
)


def loop(model: PreTrainedModel, tokenizer: PreTrainedTokenizer):
    """Main background function."""
    native_message = NativeMessage.from_stdin()

    if native_message.content == "ping":
        logging.debug("Received ping. Sending pong...")
        response = NativeMessage.from_content("pong")
        response.to_stdout()
    elif isinstance(native_message.content, dict):
        logging.debug("Received dictionary")
        response = handle_check_packages(native_message.content, tokenizer)
        logging.debug("Response: %s", response)
        NativeMessage.from_content(response).to_stdout()


def main() -> int:
    """Main entry point for `slopspotter`."""
    logging.debug("starting __main__.main()")
    parser = argparse.ArgumentParser(
        prog="slopspotter",
        description=metadata("slopspotter")["Summary"],
    )
    parser.add_argument(
        "manifest_path",
        nargs="?",
        default="",
        help="The complete path to the app manifest (generated by the extension).",
    )
    parser.add_argument(
        "browser_settings",
        nargs="?",
        default="",
        help="The extension's ID (generated by the extension).",
    )
    parser.add_argument(
        "-i",
        "--install-manifests",
        choices=SUPPORTED_BROWSERS,
        help="Set up the native host to work with the given browser.",
    )
    parser.add_argument(
        "-V",
        "--version",
        action="store_true",
        help="Print the current version and exit.",
    )
    args = parser.parse_args(sys.argv[1:])
    logging.debug("Received args: " + str(vars(args)))

    if args.version:
        print(SLOPSPOTTER_VERSION)
        return 0

    if args.install_manifests:
        manifests.install_manifests(args.install_manifests)
        return 0

    if args.manifest_path == "" or args.browser_settings == "":
        print(
            f"Invalid manifest path or settings:"
            f"\n\t- '{args.manifest_path}'"
            f"\n\t- '{args.browser_settings}'"
            "\nSee `slopspotter --help` for more information"
        )
        return 1

    model = AutoModelForCausalLM.from_pretrained(
        "Qwen/Qwen2.5-Coder-0.5B-Instruct", device_map="auto"
    )
    tokenizer = AutoTokenizer.from_pretrained(
        "Qwen/Qwen2.5-Coder-0.5B-Instruct", device_map="auto"
    )
    while True:
        loop(model, tokenizer)


if __name__ == "__main__":
    sys.exit(main())
